<script src="{{asset('asset/js/jquery-1.11.2.min.js')}}"></script>
<script src="{{asset('asset/js/jquery.bxslider.min.js')}}"></script>
<script src="{{asset('asset/js/fancybox/fancybox.js')}}"></script>
<script src="{{asset('asset/js/fancybox/helpers/jquery.fancybox-thumbs.js')}}"></script>
<script src="{{asset('asset/js/jquery.flexslider-min.js')}}"></script>
<script src="{{asset('asset/js/swiper.jquery.min.js')}}"></script>
<script src="{{asset('asset/js/jquery.waypoints.min.js')}}"></script>
<script src="{{asset('asset/js/progressbar.min.js')}}"></script>
<script src="{{asset('asset/js/ion.rangeSlider.min.js')}}"></script>
<script src="{{asset('asset/js/chosen.jquery.min.js')}}"></script>
<script src="{{asset('asset/js/jQuery.Brazzers-Carousel.js')}}"></script>
<script src="{{asset('asset/js/plugins.js')}}"></script>
<script src="{{asset('asset/js/main.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhAYvx0GmLyN5hlf6Uv_e9pPvUT3YpozE"></script>
<script src="{{asset('asset/js/gmap.js')}}"></script>
